name: 🐛 Bug Report
description: Report a bug in the TwinCAT project or documentation generation
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees:
  - Aidanvb5

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! This helps improve the demo project.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: What environment are you using?
      placeholder: "TwinCAT3 v3.5.13, Windows 10, Python 3.11"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component has the issue?
      options:
        - TwinCAT Project (PLC Code)
        - Python Scripts (Wiki Generation)
        - GitHub Actions (CI/CD)
        - Documentation (Wiki/README)
        - Project Structure
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: "When I run the wiki generator..."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Open TwinCAT project
        2. Run command '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: "The wiki should generate successfully..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: "Instead, the script failed with error..."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs/Screenshots
      description: Add any relevant logs, error messages, or screenshots
      placeholder: "Paste logs here or drag and drop screenshots"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: "This might be related to..."
    validations:
      required: false