name: ✨ Feature Request
description: Suggest a new feature or enhancement for the demo project
title: "[FEATURE] "
labels: ["enhancement", "needs-review"]
assignees:
  - Aidanvb5

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! This helps make the demo project more comprehensive.

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - TwinCAT PLC Code Enhancement
        - Documentation Generation Improvement
        - GitHub Actions/CI Enhancement
        - New Wiki Template/Format
        - Project Structure Improvement
        - New Demo Functionality
        - Other
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature
      placeholder: "Add support for..."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why would this feature be useful? What problem does it solve?
      placeholder: "This would help developers..."
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      description: Provide a detailed description of the feature
      placeholder: "The feature should work by..."
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Show how the feature would be used
      placeholder: |
        ```python
        # Example usage
        generator.new_feature()
        ```
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions?
      placeholder: "Alternative approaches could be..."
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low - Nice to have
        - Medium - Would improve the demo
        - High - Important for demonstration goals
        - Critical - Essential for project completeness
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Willingness
      description: Are you willing to help implement this feature?
      options:
        - label: I'm willing to implement this feature
        - label: I can help with testing
        - label: I can help with documentation
        - label: I need someone else to implement this

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or references
      placeholder: "Related links, mockups, etc."
    validations:
      required: false